version: '2'
services:

  app:
    build: source/.
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./source/api/:/baseimg/api/

  db:
    build: source/db/.
    volumes:
      - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: supersecure