version: '2'
services:

  app:
    build: source/.
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./source/api/:/baseimg/api/

  db:
    build: source/db/.
    restart:
      always
    ports: 
      - 5432:5432
    volumes:
      - /var/lib/postgresql
