FROM ubuntu:latest

COPY . /baseimg
WORKDIR /baseimg

#RUN apt-get update
#RUN apt-get install curl -y
#RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && apt-get install nodejs -y
#RUN apt-get install -y npm;
#RUN npm install webpack -g
#RUN npm install
CMD webpack --watch --watch-polling

#RUN apt-get install -y npm; \
#    curl -sL https://deb.nodesource.com/setup_6.x | bash - && apt-get install nodejs -y; \
#    npm install webpack -g; \
#    npm install -D babel-loader @babel/core @babel/preset-env webpack; \
#    npm install --save-dev @babel/preset-react; \
#    npm install --save-dev @babel/preset-env; \
#    npm install --save react; \
#    npm install --save prop-types; \
#    npm install --save react-dom

